version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ctf_beefest
            MYSQL_USER: tetek
            MYSQL_PASSWORD: 5E^FVZjKu4&te!Ed8p8
            MYSQL_ROOT_PASSWORD: 5E^FVZjKu4&te!Ed8p8
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 5E^FVZjKu4&te!Ed8p8
            MYSQL_ROOT_PASSWORD: 5E^FVZjKu4&te!Ed8p8
volumes:
    persistent:
