version: "3.1"
services:
    www:
        build: .
        ports: 
            - "55127:80"
        volumes:
            - ./web:/var/www/html/:ro
            - ./flag:/flag_341512514123213213:ro
            - ./config/php.ini:/usr/local/etc/php/conf.d/local.ini:ro
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: idoor
            MYSQL_USER: shtnx
            MYSQL_PASSWORD: 6^Si2OtDU2f8zD2H1Zd7&a
            MYSQL_ROOT_PASSWORD: 6^Si2OtDU2f8zD2H1Zd7&a
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
